export const message: any = {
    'item_name': 'Item Name',
    'package': 'Package',
    'quantity': 'Quantity',
    'remark': 'Remark',
    'outlet_name': 'Outlet',
    'outlet_address': 'Address',
    'order_id': 'Order ID',
    'order_by': 'Order By',
    'target_received_date': 'Target Received Date',
    'delay_day': 'Delay (days)',
    'outlet_id': 'Outlet',
    'arrived_date': 'Arrived Date',
    'order_received': 'Order Received?',
    'order_completed': 'Order Completed?',
    'warehouse_name': 'Warehouse',
    'warehouse_address': 'Address',
};