# Generated by Django 3.2.9 on 2022-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220101_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delay_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_received',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='P', max_length=100),
        ),
    ]
