# Generated by Django 3.2.9 on 2022-02-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order2_orderdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
