# Generated by Django 3.2.9 on 2022-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='status',
            field=models.CharField(default='P', max_length=100),
        ),
    ]
