# Generated by Django 3.2.9 on 2022-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='fake_col',
            field=models.CharField(default='P', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='fake_col',
            field=models.CharField(default='P', max_length=100),
        ),
    ]
