# Generated by Django 3.2.9 on 2022-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
