# Generated by Django 3.2.9 on 2022-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_item_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('template_type', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('variable', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
