# Generated by Django 3.2.9 on 2022-02-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220216_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTable',
        ),
    ]
