# Generated by Django 3.2.9 on 2022-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='variable',
            field=models.TextField(null=True),
        ),
    ]
